<?php
require_once __DIR__ . '/../../includes/init.php';
require_login();

$record_id = isset($_GET['id']) ? intval($_GET['id']) : 0;
$format = isset($_GET['format']) ? strtolower($_GET['format']) : 'csv';

// Check if user owns this land or is admin
$land_sql = "SELECT l.*, u.name as owner_name, u.email as owner_email 
            FROM land_records l 
            JOIN users u ON l.owner_id = u.user_id 
            WHERE l.record_id = ? 
            AND (l.owner_id = ? OR ? IN (SELECT user_id FROM users WHERE role = 'admin'))";
$land_stmt = mysqli_prepare($conn, $land_sql);
mysqli_stmt_bind_param($land_stmt, "iii", $record_id, $_SESSION['user_id'], $_SESSION['user_id']);
mysqli_stmt_execute($land_stmt);
$land_result = mysqli_stmt_get_result($land_stmt);
$land = mysqli_fetch_assoc($land_result);

if (!$land) {
    flash_message('error', 'Access denied or land record not found.');
    redirect('my-lands.php');
}

// Get complete land history
$history_sql = "CALL GetLandHistory(?)";
$history_stmt = mysqli_prepare($conn, $history_sql);
mysqli_stmt_bind_param($history_stmt, "i", $record_id);
mysqli_stmt_execute($history_stmt);
$history_result = mysqli_stmt_get_result($history_stmt);
$history = [];
while ($row = mysqli_fetch_assoc($history_result)) {
    $history[] = $row;
}
mysqli_stmt_close($history_stmt);

// Get ownership chain
$chain_sql = "CALL GetOwnershipChain(?)";
$chain_stmt = mysqli_prepare($conn, $chain_sql);
mysqli_stmt_bind_param($chain_stmt, "i", $record_id);
mysqli_stmt_execute($chain_stmt);
$chain_result = mysqli_stmt_get_result($chain_stmt);
$ownership_chain = [];
while ($row = mysqli_fetch_assoc($chain_result)) {
    $ownership_chain[] = $row;
}
mysqli_stmt_close($chain_stmt);

// Get splits
$splits_sql = "SELECT l.*, u.name as owner_name 
               FROM land_records l 
               JOIN users u ON l.owner_id = u.user_id 
               WHERE l.parent_record_id = ?
               ORDER BY l.registered_at DESC";
$splits_stmt = mysqli_prepare($conn, $splits_sql);
mysqli_stmt_bind_param($splits_stmt, "i", $record_id);
mysqli_stmt_execute($splits_stmt);
$splits_result = mysqli_stmt_get_result($splits_stmt);
$splits = [];
while ($row = mysqli_fetch_assoc($splits_result)) {
    $splits[] = $row;
}
mysqli_stmt_close($splits_stmt);

// Handle CSV export
if ($format === 'csv') {
    // Set headers for CSV download
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="land-history-' . preg_replace('/[^a-zA-Z0-9]/', '-', $land['parcel_no']) . '-' . date('Y-m-d') . '.csv"');
    
    // Open output stream
    $output = fopen('php://output', 'w');
    
    // Add BOM for UTF-8
    fputs($output, chr(0xEF) . chr(0xBB) . chr(0xBF));
    
    // Write header information
    fputcsv($output, ['ArdhiYetu Land Management System - Land History Report']);
    fputcsv($output, ['']);
    fputcsv($output, ['Parcel Information:']);
    fputcsv($output, ['Parcel Number:', $land['parcel_no']]);
    fputcsv($output, ['Location:', $land['location']]);
    fputcsv($output, ['Current Size:', $land['size'] . ' acres']);
    fputcsv($output, ['Current Owner:', $land['owner_name']]);
    fputcsv($output, ['Current Status:', ucfirst($land['status'])]);
    fputcsv($output, ['Report Generated:', date('F j, Y H:i:s')]);
    fputcsv($output, ['Generated By:', $_SESSION['name']]);
    fputcsv($output, ['']);
    
    // Write Ownership Chain
    if (!empty($ownership_chain)) {
        fputcsv($output, ['OWNERSHIP CHAIN:']);
        fputcsv($output, ['Depth', 'Parcel Number', 'Owner', 'Size (acres)', 'Relationship']);
        foreach ($ownership_chain as $chain) {
            $relationship = ($chain['depth'] == 1) ? 'Current' : ('Generation ' . $chain['depth']);
            fputcsv($output, [
                $chain['depth'],
                $chain['parcel_no'],
                $chain['owner_name'],
                $chain['size'],
                $relationship
            ]);
        }
        fputcsv($output, ['']);
    }
    
    // Write Splits Information
    if (!empty($splits)) {
        fputcsv($output, ['LAND SPLITS:']);
        fputcsv($output, ['Parcel Number', 'Size (acres)', 'Owner', 'Status', 'Created']);
        foreach ($splits as $split) {
            fputcsv($output, [
                $split['parcel_no'],
                $split['size'],
                $split['owner_name'],
                ucfirst($split['status']),
                date('Y-m-d', strtotime($split['registered_at']))
            ]);
        }
        fputcsv($output, ['']);
    }
    
    // Write Detailed History
    fputcsv($output, ['DETAILED HISTORY TIMELINE:']);
    fputcsv($output, [
        'Date', 
        'Event Type', 
        'Description', 
        'Transfer Type', 
        'From → To', 
        'Size Change', 
        'Notes', 
        'Document', 
        'Recorded By', 
        'Recorded At'
    ]);
    
    foreach ($history as $item) {
        // Parse the change description for ownership transfers
        $from_to = '';
        if ($item['history_type'] == 'ownership') {
            $from_to = $item['change_description'];
        }
        
        // Format size change
        $size_change = '';
        if ($item['previous_size'] || $item['new_size']) {
            $size_change = ($item['previous_size'] ? $item['previous_size'] . ' → ' : '') . 
                          $item['new_size'] . ' acres';
        }
        
        fputcsv($output, [
            $item['effective_date'],
            $item['history_type'] == 'ownership' ? 'Ownership Transfer' : 'Land Change',
            $item['change_description'],
            ucfirst(str_replace('_', ' ', $item['transfer_type'])),
            $from_to,
            $size_change,
            $item['notes'] ?? ($item['description'] ?? ''),
            $item['document_path'] ?? '',
            $item['recorded_by_name'],
            $item['recorded_at']
        ]);
    }
    
    // Write summary
    fputcsv($output, ['']);
    fputcsv($output, ['SUMMARY:']);
    fputcsv($output, ['Total History Events:', count($history)]);
    fputcsv($output, ['Ownership Transfers:', count(array_filter($history, fn($h) => $h['history_type'] == 'ownership'))]);
    fputcsv($output, ['Land Changes:', count(array_filter($history, fn($h) => $h['history_type'] == 'land_change'))]);
    fputcsv($output, ['Total Splits:', count($splits)]);
    fputcsv($output, ['Chain Length:', count($ownership_chain)]);
    
    fclose($output);
    exit;
    
} elseif ($format === 'pdf') {
    // PDF export - you would need a PDF library like TCPDF, Dompdf, or mpdf
    // This is a placeholder implementation
    
    require_once __DIR__ . '/../../includes/tcpdf/tcpdf.php';
    
    // Create new PDF document
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    
    // Set document information
    $pdf->SetCreator('ArdhiYetu Land Management System');
    $pdf->SetAuthor('ArdhiYetu');
    $pdf->SetTitle('Land History - ' . $land['parcel_no']);
    $pdf->SetSubject('Land Ownership History');
    
    // Add a page
    $pdf->AddPage();
    
    // Set font
    $pdf->SetFont('helvetica', '', 10);
    
    // Add content
    $html = '
    <h1>Land History Report</h1>
    <h2>Parcel: ' . htmlspecialchars($land['parcel_no']) . '</h2>
    <p><strong>Location:</strong> ' . htmlspecialchars($land['location']) . '</p>
    <p><strong>Current Owner:</strong> ' . htmlspecialchars($land['owner_name']) . '</p>
    <p><strong>Current Size:</strong> ' . number_format($land['size'], 2) . ' acres</p>
    <p><strong>Report Date:</strong> ' . date('F j, Y') . '</p>
    <hr>
    ';
    
    // Add history table
    $html .= '<h3>History Timeline</h3>';
    $html .= '<table border="1" cellpadding="4">';
    $html .= '<tr><th>Date</th><th>Event</th><th>Type</th><th>Details</th></tr>';
    
    foreach ($history as $item) {
        $html .= '<tr>';
        $html .= '<td>' . date('Y-m-d', strtotime($item['effective_date'])) . '</td>';
        $html .= '<td>' . htmlspecialchars($item['change_description']) . '</td>';
        $html .= '<td>' . ($item['history_type'] == 'ownership' ? 'Ownership' : 'Change') . '</td>';
        $html .= '<td>' . htmlspecialchars($item['notes'] ?? $item['description'] ?? '') . '</td>';
        $html .= '</tr>';
    }
    
    $html .= '</table>';
    
    // Output PDF
    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->Output('land-history-' . $land['parcel_no'] . '.pdf', 'D');
    exit;
    
} else {
    // Invalid format
    flash_message('error', 'Invalid export format.');
    redirect('land-history.php?id=' . $record_id);
}